openapi: 3.0.0
info:
  title: API AdoptMe
  version: 1.0.0
  description: Documentación de la API AdoptMe
servers:
  - url: http://localhost:8080
    description: Servidor de desarrollo

paths:
  /api/users/:
    get:
      summary: Obtiene una lista de usuarios
      tags:
        - Users
      responses:
        "200":
          description: La operación fue exitosa, se retorna un arreglo de los usuarios.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        "500":
          description: Error inesperado en el servidor, no se pudo manejar el proceso.

  /api/users/{uid}:
    get:
      summary: Obtiene un usuario por su ID
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          description: Id del usuario
          schema:
            type: string
      responses:
        "200":
          description: La operación fue exitosa, se retorna un usuario por su ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "500":
          description: Error inesperado en el servidor, no se pudo manejar el proceso.

    put:
      summary: Actualiza un usuario por su ID
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          description: Id del usuario que se desea actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
            example:
              first_name: "Lucía"
              last_name: "Fernández"
              email: "lucia.fer@gmail.com"
              password: "secreto123"
              role: "user"
              pets: ["perro"]
      responses:
        "200":
          description: Usuario actualizado correctamente
        "400":
          description: Error en la solicitud. Datos inválidos.
        "404":
          description: Usuario no encontrado.
        "500":
          description: Error interno del servidor.

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: La PK del usuario auto-generada por MongoDB.
          example: "657872b1244ab4694ca2e659"
        first_name:
          type: string
          description: Nombre del usuario.
          example: "Valentín"
        last_name:
          type: string
          description: Apellido del usuario.
          example: "Silva"
        email:
          type: string
          description: Email del usuario.
          example: "valen.silva93@mail.com"
        password:
          type: string
          description: Contraseña encriptada del usuario.
          example: "$2b$10$09PBC9szgGEI1D4nRFE4teX7r8n2ikGTXn2ZKU1kL3WbH4N8WvT9C"
        role:
          type: string
          description: Rol del usuario.
          example: "user"
        pets:
          type: array
          description: Lista de mascotas asociadas al usuario.
          items:
            type: string
          example: ["perro"]
